name: Python package

on: [push]

jobs:
  check:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: install dependencies
        run: pip install -U setuptools && pip install -e '.[tests]'

      - name: run tests
        run: python -m pytest -v --cov src

      - name: run isort
        run: python -m isort . --check

      - name: run black
        run: python -m black . --check

      - name: run ruff
        run: python -m ruff .

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

